// Generated by gencpp from file lower_limb_kinematics/foot_rp.msg
// DO NOT EDIT!


#ifndef LOWER_LIMB_KINEMATICS_MESSAGE_FOOT_RP_H
#define LOWER_LIMB_KINEMATICS_MESSAGE_FOOT_RP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lower_limb_kinematics
{
template <class ContainerAllocator>
struct foot_rp_
{
  typedef foot_rp_<ContainerAllocator> Type;

  foot_rp_()
    : roll(0.0)
    , pitch(0.0)  {
    }
  foot_rp_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;




  typedef boost::shared_ptr< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> const> ConstPtr;

}; // struct foot_rp_

typedef ::lower_limb_kinematics::foot_rp_<std::allocator<void> > foot_rp;

typedef boost::shared_ptr< ::lower_limb_kinematics::foot_rp > foot_rpPtr;
typedef boost::shared_ptr< ::lower_limb_kinematics::foot_rp const> foot_rpConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lower_limb_kinematics::foot_rp_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lower_limb_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lower_limb_kinematics': ['/home/ashwin/catkin_ws/src/lower_limb_kinematics/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f5aa311af37faead3f9e90f420c9603";
  }

  static const char* value(const ::lower_limb_kinematics::foot_rp_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f5aa311af37faeaULL;
  static const uint64_t static_value2 = 0xd3f9e90f420c9603ULL;
};

template<class ContainerAllocator>
struct DataType< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lower_limb_kinematics/foot_rp";
  }

  static const char* value(const ::lower_limb_kinematics::foot_rp_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n\
float64 pitch\n\
";
  }

  static const char* value(const ::lower_limb_kinematics::foot_rp_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct foot_rp_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lower_limb_kinematics::foot_rp_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lower_limb_kinematics::foot_rp_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOWER_LIMB_KINEMATICS_MESSAGE_FOOT_RP_H
