// Generated by gencpp from file lower_limb_kinematics/imu_sample.msg
// DO NOT EDIT!


#ifndef LOWER_LIMB_KINEMATICS_MESSAGE_IMU_SAMPLE_H
#define LOWER_LIMB_KINEMATICS_MESSAGE_IMU_SAMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lower_limb_kinematics
{
template <class ContainerAllocator>
struct imu_sample_
{
  typedef imu_sample_<ContainerAllocator> Type;

  imu_sample_()
    : imu_sample()
    , time(0.0)  {
      imu_sample.assign(0.0);
  }
  imu_sample_(const ContainerAllocator& _alloc)
    : imu_sample()
    , time(0.0)  {
  (void)_alloc;
      imu_sample.assign(0.0);
  }



   typedef boost::array<float, 9>  _imu_sample_type;
  _imu_sample_type imu_sample;

   typedef float _time_type;
  _time_type time;




  typedef boost::shared_ptr< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> const> ConstPtr;

}; // struct imu_sample_

typedef ::lower_limb_kinematics::imu_sample_<std::allocator<void> > imu_sample;

typedef boost::shared_ptr< ::lower_limb_kinematics::imu_sample > imu_samplePtr;
typedef boost::shared_ptr< ::lower_limb_kinematics::imu_sample const> imu_sampleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lower_limb_kinematics::imu_sample_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lower_limb_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lower_limb_kinematics': ['/home/ashwin/catkin_ws/src/lower_limb_kinematics/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e7fe6e4f341022722ea2e4be6e80f82";
  }

  static const char* value(const ::lower_limb_kinematics::imu_sample_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e7fe6e4f3410227ULL;
  static const uint64_t static_value2 = 0x22ea2e4be6e80f82ULL;
};

template<class ContainerAllocator>
struct DataType< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lower_limb_kinematics/imu_sample";
  }

  static const char* value(const ::lower_limb_kinematics::imu_sample_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[9] imu_sample\n\
float32 time\n\
";
  }

  static const char* value(const ::lower_limb_kinematics::imu_sample_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imu_sample);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct imu_sample_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lower_limb_kinematics::imu_sample_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lower_limb_kinematics::imu_sample_<ContainerAllocator>& v)
  {
    s << indent << "imu_sample[]" << std::endl;
    for (size_t i = 0; i < v.imu_sample.size(); ++i)
    {
      s << indent << "  imu_sample[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.imu_sample[i]);
    }
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOWER_LIMB_KINEMATICS_MESSAGE_IMU_SAMPLE_H
