// Generated by gencpp from file lower_limb_kinematics/quaternion_sample.msg
// DO NOT EDIT!


#ifndef LOWER_LIMB_KINEMATICS_MESSAGE_QUATERNION_SAMPLE_H
#define LOWER_LIMB_KINEMATICS_MESSAGE_QUATERNION_SAMPLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lower_limb_kinematics
{
template <class ContainerAllocator>
struct quaternion_sample_
{
  typedef quaternion_sample_<ContainerAllocator> Type;

  quaternion_sample_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
    }
  quaternion_sample_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , w(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _w_type;
  _w_type w;




  typedef boost::shared_ptr< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> const> ConstPtr;

}; // struct quaternion_sample_

typedef ::lower_limb_kinematics::quaternion_sample_<std::allocator<void> > quaternion_sample;

typedef boost::shared_ptr< ::lower_limb_kinematics::quaternion_sample > quaternion_samplePtr;
typedef boost::shared_ptr< ::lower_limb_kinematics::quaternion_sample const> quaternion_sampleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lower_limb_kinematics

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'lower_limb_kinematics': ['/home/ashwin/catkin_ws/src/lower_limb_kinematics/msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a70de85a9dd451c31fa86cab10a939";
  }

  static const char* value(const ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a70de85a9dd451ULL;
  static const uint64_t static_value2 = 0xc31fa86cab10a939ULL;
};

template<class ContainerAllocator>
struct DataType< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lower_limb_kinematics/quaternion_sample";
  }

  static const char* value(const ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
float32 w\n\
";
  }

  static const char* value(const ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.w);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct quaternion_sample_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lower_limb_kinematics::quaternion_sample_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LOWER_LIMB_KINEMATICS_MESSAGE_QUATERNION_SAMPLE_H
